default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  reaping_frequency: 10
  timeout: 5000
  username: <%= ENV["PROPS_PG_USERNAME"] %>
  password: <%= ENV["PROPS_PG_PASSWORD"] %>

development:
  <<: *default
  database: props_development

production:
  <<: *default
  database: props_production
