# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86cc6b0adcdfa30ee4cb0c51fca5e7d5e62c5bb4edc84ece4b7dededc3726860ad939503308f6588d6bed8d6089edaf814a06b36aac48f5003e61bc4a297b3e3

test:
  secret_key_base: 38203e223b2232e184d103311bb4444b72a93246825b8f0ac7922d911faa2db7788f06b870e6c3a0232e41bdb96492cbd21576607ad6bd82f89bbe03c6be338f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
